version: '3.7'
services:

  zookeeper:
    image: 'bitnami/zookeeper:latest'
    restart: always
    environment:
      ALLOW_ANONYMOUS_LOGIN: "yes"
    ports:
      - 2181:2181
      - 2888:2888
      - 3888:3888

  kafka:
    image: 'bitnami/kafka:latest'
    restart: always
    depends_on:
      - zookeeper
    environment:
      ALLOW_PLAINTEXT_LISTENER: "yes"
      KAFKA_CFG_ZOOKEEPER_CONNECT: "zookeeper:2181"
    ports:
      - 9092:9092

  flink-182:
    container_name: flink-182
    build: ./flink-182
    depends_on:
      - zookeeper
      - kafka
    environment:
      PORT: 3000
      kafkaHost: kafka:9092
    ports:
      - "3000:3000" 
    volumes:
      - "./flink-182/src:/app/src"
  
  server-pruebarecepcionkafka:
    container_name: server-pruebarecepcionkafka
    build: ./server-pruebarecepcionkafka
    depends_on:
      - zookeeper
      - kafka
    environment:
      PORT: 5000
      kafkaHost: kafka:9092
    ports:
      - "5000:5000" 
    volumes:
      - "./server-pruebarecepcionkafka/src:/app/src"